/*
 * This file is generated by jOOQ.
 */
package com.meidianyi.shop.common.pojo.shop.table;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 科室
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DoctorTitleDo implements Serializable {

    private static final long serialVersionUID = -137897793;

    private Integer   id;
    private String    name;
    private String    code;
    private Integer   first;
    private Byte      isDelete;
    private Timestamp createTime;
    private Timestamp updateTime;

    public DoctorTitleDo() {}

    public DoctorTitleDo(DoctorTitleDo value) {
        this.id = value.id;
        this.name = value.name;
        this.code = value.code;
        this.isDelete = value.isDelete;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public DoctorTitleDo(
        Integer   id,
        String    name,
        String    code,
        Byte      isDelete,
        Timestamp createTime,
        Timestamp updateTime
    ) {
        this.id = id;
        this.name = name;
        this.code = code;
        this.isDelete = isDelete;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public Byte getIsDelete() {
        return this.isDelete;
    }

    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DoctorTitleDo (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(code);
        sb.append(", ").append(isDelete);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
