/*
 * This file is generated by jOOQ.
 */
package com.meidianyi.shop.db.main.tables;


import com.meidianyi.shop.db.main.Indexes;
import com.meidianyi.shop.db.main.Keys;
import com.meidianyi.shop.db.main.MiniMain;
import com.meidianyi.shop.db.main.tables.records.AliMiniAuthShopRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AliMiniAuthShop extends TableImpl<AliMiniAuthShopRecord> {

    private static final long serialVersionUID = 1611241750;

    /**
     * The reference instance of <code>mini_main.b2c_ali_mini_auth_shop</code>
     */
    public static final AliMiniAuthShop ALI_MINI_AUTH_SHOP = new AliMiniAuthShop();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AliMiniAuthShopRecord> getRecordType() {
        return AliMiniAuthShopRecord.class;
    }

    /**
     * The column <code>mini_main.b2c_ali_mini_auth_shop.auth_app_id</code>. 授权商户的appid	
     */
    public final TableField<AliMiniAuthShopRecord, String> AUTH_APP_ID = createField("auth_app_id", org.jooq.impl.SQLDataType.VARCHAR(191).nullable(false), this, "授权商户的appid	");

    /**
     * The column <code>mini_main.b2c_ali_mini_auth_shop.user_id</code>. 授权商户的user_id	
     */
    public final TableField<AliMiniAuthShopRecord, String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR(191), this, "授权商户的user_id	");

    /**
     * The column <code>mini_main.b2c_ali_mini_auth_shop.app_auth_token</code>. 应用授权令牌	
     */
    public final TableField<AliMiniAuthShopRecord, String> APP_AUTH_TOKEN = createField("app_auth_token", org.jooq.impl.SQLDataType.VARCHAR(191), this, "应用授权令牌	");

    /**
     * The column <code>mini_main.b2c_ali_mini_auth_shop.app_refresh_token</code>. 刷新令牌
     */
    public final TableField<AliMiniAuthShopRecord, String> APP_REFRESH_TOKEN = createField("app_refresh_token", org.jooq.impl.SQLDataType.VARCHAR(191), this, "刷新令牌");

    /**
     * The column <code>mini_main.b2c_ali_mini_auth_shop.expires_in_time</code>. 应用授权令牌的过期时间
     */
    public final TableField<AliMiniAuthShopRecord, Timestamp> EXPIRES_IN_TIME = createField("expires_in_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "应用授权令牌的过期时间");

    /**
     * The column <code>mini_main.b2c_ali_mini_auth_shop.re_expires_in_time</code>. 刷新令牌的过期时间
     */
    public final TableField<AliMiniAuthShopRecord, Timestamp> RE_EXPIRES_IN_TIME = createField("re_expires_in_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "刷新令牌的过期时间");

    /**
     * The column <code>mini_main.b2c_ali_mini_auth_shop.shop_id</code>. 店铺Id
     */
    public final TableField<AliMiniAuthShopRecord, Integer> SHOP_ID = createField("shop_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "店铺Id");

    /**
     * The column <code>mini_main.b2c_ali_mini_auth_shop.app_name</code>. 代商家创建的小程序应用名称
     */
    public final TableField<AliMiniAuthShopRecord, String> APP_NAME = createField("app_name", org.jooq.impl.SQLDataType.VARCHAR(191), this, "代商家创建的小程序应用名称");

    /**
     * The column <code>mini_main.b2c_ali_mini_auth_shop.app_english_name</code>. 小程序英文名称，长度3~20个字符	
     */
    public final TableField<AliMiniAuthShopRecord, String> APP_ENGLISH_NAME = createField("app_english_name", org.jooq.impl.SQLDataType.VARCHAR(191), this, "小程序英文名称，长度3~20个字符	");

    /**
     * The column <code>mini_main.b2c_ali_mini_auth_shop.app_category_ids</code>. 小程序应用类目，参数格式：一级类目_二级类目。
     */
    public final TableField<AliMiniAuthShopRecord, String> APP_CATEGORY_IDS = createField("app_category_ids", org.jooq.impl.SQLDataType.VARCHAR(191), this, "小程序应用类目，参数格式：一级类目_二级类目。");

    /**
     * The column <code>mini_main.b2c_ali_mini_auth_shop.app_slogan</code>. 代商家创建的小程序的简介，请用一句话简要描述小程序提供的服务；应用上架后一个自然月可修改5次（10~32个字符）	
     */
    public final TableField<AliMiniAuthShopRecord, String> APP_SLOGAN = createField("app_slogan", org.jooq.impl.SQLDataType.VARCHAR(191), this, "代商家创建的小程序的简介，请用一句话简要描述小程序提供的服务；应用上架后一个自然月可修改5次（10~32个字符）	");

    /**
     * The column <code>mini_main.b2c_ali_mini_auth_shop.service_phone</code>. 商家小程序的客服电话，推荐填写商家小程序客服电话和邮箱，可以二选一填写，但不能同时为空
     */
    public final TableField<AliMiniAuthShopRecord, String> SERVICE_PHONE = createField("service_phone", org.jooq.impl.SQLDataType.VARCHAR(191).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "商家小程序的客服电话，推荐填写商家小程序客服电话和邮箱，可以二选一填写，但不能同时为空");

    /**
     * The column <code>mini_main.b2c_ali_mini_auth_shop.service_email</code>. 商家小程序客服邮箱 
     */
    public final TableField<AliMiniAuthShopRecord, String> SERVICE_EMAIL = createField("service_email", org.jooq.impl.SQLDataType.VARCHAR(191).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "商家小程序客服邮箱 ");

    /**
     * The column <code>mini_main.b2c_ali_mini_auth_shop.app_logo</code>. 商家小程序应用图标，最大256KB,png、jpeg、jpg格式，建议上传像素为180*180
     */
    public final TableField<AliMiniAuthShopRecord, String> APP_LOGO = createField("app_logo", org.jooq.impl.SQLDataType.VARCHAR(191), this, "商家小程序应用图标，最大256KB,png、jpeg、jpg格式，建议上传像素为180*180");

    /**
     * The column <code>mini_main.b2c_ali_mini_auth_shop.app_desc</code>. 商家小程序描述信息，简要描述小程序主要功能（20-200个字）
     */
    public final TableField<AliMiniAuthShopRecord, String> APP_DESC = createField("app_desc", org.jooq.impl.SQLDataType.VARCHAR(191), this, "商家小程序描述信息，简要描述小程序主要功能（20-200个字）");

    /**
     * The column <code>mini_main.b2c_ali_mini_auth_shop.is_auth_ok</code>. 是否授权成功,如果公众号后台取消授权，则为0
     */
    public final TableField<AliMiniAuthShopRecord, Byte> IS_AUTH_OK = createField("is_auth_ok", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.TINYINT)), this, "是否授权成功,如果公众号后台取消授权，则为0");

    /**
     * The column <code>mini_main.b2c_ali_mini_auth_shop.last_auth_time</code>. 最后成功授权的时间
     */
    public final TableField<AliMiniAuthShopRecord, Timestamp> LAST_AUTH_TIME = createField("last_auth_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "最后成功授权的时间");

    /**
     * The column <code>mini_main.b2c_ali_mini_auth_shop.last_cancel_auth_time</code>. 最后取消授权的时间
     */
    public final TableField<AliMiniAuthShopRecord, Timestamp> LAST_CANCEL_AUTH_TIME = createField("last_cancel_auth_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "最后取消授权的时间");

    /**
     * The column <code>mini_main.b2c_ali_mini_auth_shop.app_version</code>. 小程序版本
     */
    public final TableField<AliMiniAuthShopRecord, String> APP_VERSION = createField("app_version", org.jooq.impl.SQLDataType.VARCHAR(191), this, "小程序版本");

    /**
     * The column <code>mini_main.b2c_ali_mini_auth_shop.status</code>. 小程序版本状态，INIT-开发中，AUDITING-审核中，WAIT_RELEASE-审核通过，AUDIT_REJECT-审核驳回，RELEASE-已上架，GRAY-灰度中，OFFLINE-下架	
     */
    public final TableField<AliMiniAuthShopRecord, String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR(191), this, "小程序版本状态，INIT-开发中，AUDITING-审核中，WAIT_RELEASE-审核通过，AUDIT_REJECT-审核驳回，RELEASE-已上架，GRAY-灰度中，OFFLINE-下架	");

    /**
     * The column <code>mini_main.b2c_ali_mini_auth_shop.detail_info</code>. 小程序详细信息，参考https://docs.open.alipay.com/api_49/alipay.open.mini.version.detail.query/
     */
    public final TableField<AliMiniAuthShopRecord, String> DETAIL_INFO = createField("detail_info", org.jooq.impl.SQLDataType.CLOB, this, "小程序详细信息，参考https://docs.open.alipay.com/api_49/alipay.open.mini.version.detail.query/");

    /**
     * The column <code>mini_main.b2c_ali_mini_auth_shop.experience_status</code>. 体验版打包状态，expVersionPackged-体验版打包成功，expVersionPackaging-体验版打包中，notExpVersion-非体验版
     */
    public final TableField<AliMiniAuthShopRecord, String> EXPERIENCE_STATUS = createField("experience_status", org.jooq.impl.SQLDataType.VARCHAR(191).defaultValue(org.jooq.impl.DSL.inline("notExpVersion", org.jooq.impl.SQLDataType.VARCHAR)), this, "体验版打包状态，expVersionPackged-体验版打包成功，expVersionPackaging-体验版打包中，notExpVersion-非体验版");

    /**
     * The column <code>mini_main.b2c_ali_mini_auth_shop.tester</code>. 小程序体验者列表,json存储
     */
    public final TableField<AliMiniAuthShopRecord, String> TESTER = createField("tester", org.jooq.impl.SQLDataType.CLOB, this, "小程序体验者列表,json存储");

    /**
     * The column <code>mini_main.b2c_ali_mini_auth_shop.exp_qr_code_url</code>. 小程序体验版二维码地址	
     */
    public final TableField<AliMiniAuthShopRecord, String> EXP_QR_CODE_URL = createField("exp_qr_code_url", org.jooq.impl.SQLDataType.VARCHAR(191), this, "小程序体验版二维码地址	");

    /**
     * The column <code>mini_main.b2c_ali_mini_auth_shop.create_time</code>.
     */
    public final TableField<AliMiniAuthShopRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>mini_main.b2c_ali_mini_auth_shop</code> table reference
     */
    public AliMiniAuthShop() {
        this(DSL.name("b2c_ali_mini_auth_shop"), null);
    }

    /**
     * Create an aliased <code>mini_main.b2c_ali_mini_auth_shop</code> table reference
     */
    public AliMiniAuthShop(String alias) {
        this(DSL.name(alias), ALI_MINI_AUTH_SHOP);
    }

    /**
     * Create an aliased <code>mini_main.b2c_ali_mini_auth_shop</code> table reference
     */
    public AliMiniAuthShop(Name alias) {
        this(alias, ALI_MINI_AUTH_SHOP);
    }

    private AliMiniAuthShop(Name alias, Table<AliMiniAuthShopRecord> aliased) {
        this(alias, aliased, null);
    }

    private AliMiniAuthShop(Name alias, Table<AliMiniAuthShopRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> AliMiniAuthShop(Table<O> child, ForeignKey<O, AliMiniAuthShopRecord> key) {
        super(child, key, ALI_MINI_AUTH_SHOP);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MiniMain.MINI_MAIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ALI_MINI_AUTH_SHOP_PRIMARY, Indexes.ALI_MINI_AUTH_SHOP_SHOP_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AliMiniAuthShopRecord> getPrimaryKey() {
        return Keys.KEY_B2C_ALI_MINI_AUTH_SHOP_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AliMiniAuthShopRecord>> getKeys() {
        return Arrays.<UniqueKey<AliMiniAuthShopRecord>>asList(Keys.KEY_B2C_ALI_MINI_AUTH_SHOP_PRIMARY, Keys.KEY_B2C_ALI_MINI_AUTH_SHOP_SHOP_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AliMiniAuthShop as(String alias) {
        return new AliMiniAuthShop(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AliMiniAuthShop as(Name alias) {
        return new AliMiniAuthShop(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AliMiniAuthShop rename(String name) {
        return new AliMiniAuthShop(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AliMiniAuthShop rename(Name name) {
        return new AliMiniAuthShop(name, null);
    }
}
