/*
 * This file is generated by jOOQ.
 */
package com.meidianyi.shop.db.main.tables.records;


import com.meidianyi.shop.db.main.tables.MpDistributionVisit;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MpDistributionVisitRecord extends TableRecordImpl<MpDistributionVisitRecord> implements Record3<String, String, Timestamp> {

    private static final long serialVersionUID = -1689446265;

    /**
     * Setter for <code>mini_main.b2c_mp_distribution_visit.ref_date</code>. 时间，如："20180313"
     */
    public void setRefDate(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>mini_main.b2c_mp_distribution_visit.ref_date</code>. 时间，如："20180313"
     */
    public String getRefDate() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mini_main.b2c_mp_distribution_visit.list</code>. 存入所有类型的指标情况
     */
    public void setList(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mini_main.b2c_mp_distribution_visit.list</code>. 存入所有类型的指标情况
     */
    public String getList() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mini_main.b2c_mp_distribution_visit.add_time</code>. 添加时间
     */
    public void setAddTime(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>mini_main.b2c_mp_distribution_visit.add_time</code>. 添加时间
     */
    public Timestamp getAddTime() {
        return (Timestamp) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, Timestamp> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, Timestamp> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return MpDistributionVisit.MP_DISTRIBUTION_VISIT.REF_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return MpDistributionVisit.MP_DISTRIBUTION_VISIT.LIST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return MpDistributionVisit.MP_DISTRIBUTION_VISIT.ADD_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getRefDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getList();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getAddTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getRefDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getList();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getAddTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MpDistributionVisitRecord value1(String value) {
        setRefDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MpDistributionVisitRecord value2(String value) {
        setList(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MpDistributionVisitRecord value3(Timestamp value) {
        setAddTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MpDistributionVisitRecord values(String value1, String value2, Timestamp value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MpDistributionVisitRecord
     */
    public MpDistributionVisitRecord() {
        super(MpDistributionVisit.MP_DISTRIBUTION_VISIT);
    }

    /**
     * Create a detached, initialised MpDistributionVisitRecord
     */
    public MpDistributionVisitRecord(String refDate, String list, Timestamp addTime) {
        super(MpDistributionVisit.MP_DISTRIBUTION_VISIT);

        set(0, refDate);
        set(1, list);
        set(2, addTime);
    }
}
