/*
 * This file is generated by jOOQ.
 */
package com.meidianyi.shop.db.shop.tables.records;


import com.meidianyi.shop.db.shop.tables.BargainGoods;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BargainGoodsRecord extends UpdatableRecordImpl<BargainGoodsRecord> implements Record8<Integer, Integer, Integer, BigDecimal, BigDecimal, Integer, Integer, Timestamp> {

    private static final long serialVersionUID = 1405681800;

    /**
     * Setter for <code>mini_shop_471752.b2c_bargain_goods.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_bargain_goods.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_bargain_goods.bargain_id</code>.
     */
    public void setBargainId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_bargain_goods.bargain_id</code>.
     */
    public Integer getBargainId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_bargain_goods.goods_id</code>.
     */
    public void setGoodsId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_bargain_goods.goods_id</code>.
     */
    public Integer getGoodsId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_bargain_goods.expectation_price</code>.
     */
    public void setExpectationPrice(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_bargain_goods.expectation_price</code>.
     */
    public BigDecimal getExpectationPrice() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_bargain_goods.floor_price</code>.
     */
    public void setFloorPrice(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_bargain_goods.floor_price</code>.
     */
    public BigDecimal getFloorPrice() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_bargain_goods.stock</code>.
     */
    public void setStock(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_bargain_goods.stock</code>.
     */
    public Integer getStock() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_bargain_goods.sale_num</code>.
     */
    public void setSaleNum(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_bargain_goods.sale_num</code>.
     */
    public Integer getSaleNum() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_bargain_goods.update_time</code>.
     */
    public void setUpdateTime(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_bargain_goods.update_time</code>.
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, Integer, BigDecimal, BigDecimal, Integer, Integer, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, Integer, BigDecimal, BigDecimal, Integer, Integer, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return BargainGoods.BARGAIN_GOODS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return BargainGoods.BARGAIN_GOODS.BARGAIN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return BargainGoods.BARGAIN_GOODS.GOODS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return BargainGoods.BARGAIN_GOODS.EXPECTATION_PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field5() {
        return BargainGoods.BARGAIN_GOODS.FLOOR_PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return BargainGoods.BARGAIN_GOODS.STOCK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return BargainGoods.BARGAIN_GOODS.SALE_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return BargainGoods.BARGAIN_GOODS.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getBargainId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getGoodsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component4() {
        return getExpectationPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component5() {
        return getFloorPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getStock();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getSaleNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getBargainId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getGoodsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getExpectationPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value5() {
        return getFloorPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getStock();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getSaleNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BargainGoodsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BargainGoodsRecord value2(Integer value) {
        setBargainId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BargainGoodsRecord value3(Integer value) {
        setGoodsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BargainGoodsRecord value4(BigDecimal value) {
        setExpectationPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BargainGoodsRecord value5(BigDecimal value) {
        setFloorPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BargainGoodsRecord value6(Integer value) {
        setStock(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BargainGoodsRecord value7(Integer value) {
        setSaleNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BargainGoodsRecord value8(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BargainGoodsRecord values(Integer value1, Integer value2, Integer value3, BigDecimal value4, BigDecimal value5, Integer value6, Integer value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BargainGoodsRecord
     */
    public BargainGoodsRecord() {
        super(BargainGoods.BARGAIN_GOODS);
    }

    /**
     * Create a detached, initialised BargainGoodsRecord
     */
    public BargainGoodsRecord(Integer id, Integer bargainId, Integer goodsId, BigDecimal expectationPrice, BigDecimal floorPrice, Integer stock, Integer saleNum, Timestamp updateTime) {
        super(BargainGoods.BARGAIN_GOODS);

        set(0, id);
        set(1, bargainId);
        set(2, goodsId);
        set(3, expectationPrice);
        set(4, floorPrice);
        set(5, stock);
        set(6, saleNum);
        set(7, updateTime);
    }
}
