/*
 * This file is generated by jOOQ.
 */
package com.meidianyi.shop.db.shop.tables.records;


import com.meidianyi.shop.db.shop.tables.Channel;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChannelRecord extends UpdatableRecordImpl<ChannelRecord> implements Record10<Integer, Integer, Integer, String, Byte, String, Byte, Timestamp, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1012477114;

    /**
     * Setter for <code>mini_shop_471752.b2c_channel.id</code>. 渠道页id
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_channel.id</code>. 渠道页id
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_channel.page_id</code>. page_id
     */
    public void setPageId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_channel.page_id</code>. page_id
     */
    public Integer getPageId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_channel.goods_id</code>. goods_id
     */
    public void setGoodsId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_channel.goods_id</code>. goods_id
     */
    public Integer getGoodsId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_channel.channel_name</code>. 渠道页名称
     */
    public void setChannelName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_channel.channel_name</code>. 渠道页名称
     */
    public String getChannelName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_channel.source_type</code>. 来源类型 0自定义 1商品
     */
    public void setSourceType(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_channel.source_type</code>. 来源类型 0自定义 1商品
     */
    public Byte getSourceType() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_channel.share</code>. 分享码
     */
    public void setShare(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_channel.share</code>. 分享码
     */
    public String getShare() {
        return (String) get(5);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_channel.del_flag</code>. 0正常，1废除
     */
    public void setDelFlag(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_channel.del_flag</code>. 0正常，1废除
     */
    public Byte getDelFlag() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_channel.del_time</code>. 删除时间
     */
    public void setDelTime(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_channel.del_time</code>. 删除时间
     */
    public Timestamp getDelTime() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_channel.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_channel.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_channel.update_time</code>. 最后修改时间
     */
    public void setUpdateTime(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_channel.update_time</code>. 最后修改时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, Integer, String, Byte, String, Byte, Timestamp, Timestamp, Timestamp> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, Integer, String, Byte, String, Byte, Timestamp, Timestamp, Timestamp> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Channel.CHANNEL.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Channel.CHANNEL.PAGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Channel.CHANNEL.GOODS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Channel.CHANNEL.CHANNEL_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return Channel.CHANNEL.SOURCE_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Channel.CHANNEL.SHARE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field7() {
        return Channel.CHANNEL.DEL_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return Channel.CHANNEL.DEL_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return Channel.CHANNEL.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return Channel.CHANNEL.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getPageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getGoodsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getChannelName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component5() {
        return getSourceType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getShare();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component7() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getDelTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getPageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getGoodsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getChannelName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getSourceType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getShare();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value7() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getDelTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChannelRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChannelRecord value2(Integer value) {
        setPageId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChannelRecord value3(Integer value) {
        setGoodsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChannelRecord value4(String value) {
        setChannelName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChannelRecord value5(Byte value) {
        setSourceType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChannelRecord value6(String value) {
        setShare(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChannelRecord value7(Byte value) {
        setDelFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChannelRecord value8(Timestamp value) {
        setDelTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChannelRecord value9(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChannelRecord value10(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChannelRecord values(Integer value1, Integer value2, Integer value3, String value4, Byte value5, String value6, Byte value7, Timestamp value8, Timestamp value9, Timestamp value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChannelRecord
     */
    public ChannelRecord() {
        super(Channel.CHANNEL);
    }

    /**
     * Create a detached, initialised ChannelRecord
     */
    public ChannelRecord(Integer id, Integer pageId, Integer goodsId, String channelName, Byte sourceType, String share, Byte delFlag, Timestamp delTime, Timestamp createTime, Timestamp updateTime) {
        super(Channel.CHANNEL);

        set(0, id);
        set(1, pageId);
        set(2, goodsId);
        set(3, channelName);
        set(4, sourceType);
        set(5, share);
        set(6, delFlag);
        set(7, delTime);
        set(8, createTime);
        set(9, updateTime);
    }
}
