/*
 * This file is generated by jOOQ.
 */
package com.meidianyi.shop.db.shop.tables.records;


import com.meidianyi.shop.db.shop.tables.DoctorTotalRebate;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 医师返利数据表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DoctorTotalRebateRecord extends UpdatableRecordImpl<DoctorTotalRebateRecord> implements Record8<Integer, Integer, BigDecimal, BigDecimal, BigDecimal, Byte, Timestamp, Timestamp> {

    private static final long serialVersionUID = -114802304;

    /**
     * Setter for <code>mini_shop_471752.b2c_doctor_total_rebate.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_doctor_total_rebate.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_doctor_total_rebate.doctor_id</code>. 医师id
     */
    public void setDoctorId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_doctor_total_rebate.doctor_id</code>. 医师id
     */
    public Integer getDoctorId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_doctor_total_rebate.total_money</code>. 累计获得返利金额
     */
    public void setTotalMoney(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_doctor_total_rebate.total_money</code>. 累计获得返利金额
     */
    public BigDecimal getTotalMoney() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_doctor_total_rebate.blocked_money</code>. 冻结余额
     */
    public void setBlockedMoney(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_doctor_total_rebate.blocked_money</code>. 冻结余额
     */
    public BigDecimal getBlockedMoney() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_doctor_total_rebate.final_money</code>. 总返利金额，total_money为提现后金额
     */
    public void setFinalMoney(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_doctor_total_rebate.final_money</code>. 总返利金额，total_money为提现后金额
     */
    public BigDecimal getFinalMoney() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_doctor_total_rebate.is_delete</code>.
     */
    public void setIsDelete(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_doctor_total_rebate.is_delete</code>.
     */
    public Byte getIsDelete() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_doctor_total_rebate.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_doctor_total_rebate.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_doctor_total_rebate.update_time</code>. 最后修改时间
     */
    public void setUpdateTime(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_doctor_total_rebate.update_time</code>. 最后修改时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, BigDecimal, BigDecimal, BigDecimal, Byte, Timestamp, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, BigDecimal, BigDecimal, BigDecimal, Byte, Timestamp, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return DoctorTotalRebate.DOCTOR_TOTAL_REBATE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return DoctorTotalRebate.DOCTOR_TOTAL_REBATE.DOCTOR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return DoctorTotalRebate.DOCTOR_TOTAL_REBATE.TOTAL_MONEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return DoctorTotalRebate.DOCTOR_TOTAL_REBATE.BLOCKED_MONEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field5() {
        return DoctorTotalRebate.DOCTOR_TOTAL_REBATE.FINAL_MONEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field6() {
        return DoctorTotalRebate.DOCTOR_TOTAL_REBATE.IS_DELETE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return DoctorTotalRebate.DOCTOR_TOTAL_REBATE.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return DoctorTotalRebate.DOCTOR_TOTAL_REBATE.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getDoctorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component3() {
        return getTotalMoney();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component4() {
        return getBlockedMoney();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component5() {
        return getFinalMoney();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component6() {
        return getIsDelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getDoctorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getTotalMoney();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getBlockedMoney();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value5() {
        return getFinalMoney();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value6() {
        return getIsDelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DoctorTotalRebateRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DoctorTotalRebateRecord value2(Integer value) {
        setDoctorId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DoctorTotalRebateRecord value3(BigDecimal value) {
        setTotalMoney(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DoctorTotalRebateRecord value4(BigDecimal value) {
        setBlockedMoney(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DoctorTotalRebateRecord value5(BigDecimal value) {
        setFinalMoney(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DoctorTotalRebateRecord value6(Byte value) {
        setIsDelete(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DoctorTotalRebateRecord value7(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DoctorTotalRebateRecord value8(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DoctorTotalRebateRecord values(Integer value1, Integer value2, BigDecimal value3, BigDecimal value4, BigDecimal value5, Byte value6, Timestamp value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DoctorTotalRebateRecord
     */
    public DoctorTotalRebateRecord() {
        super(DoctorTotalRebate.DOCTOR_TOTAL_REBATE);
    }

    /**
     * Create a detached, initialised DoctorTotalRebateRecord
     */
    public DoctorTotalRebateRecord(Integer id, Integer doctorId, BigDecimal totalMoney, BigDecimal blockedMoney, BigDecimal finalMoney, Byte isDelete, Timestamp createTime, Timestamp updateTime) {
        super(DoctorTotalRebate.DOCTOR_TOTAL_REBATE);

        set(0, id);
        set(1, doctorId);
        set(2, totalMoney);
        set(3, blockedMoney);
        set(4, finalMoney);
        set(5, isDelete);
        set(6, createTime);
        set(7, updateTime);
    }
}
