/*
 * This file is generated by jOOQ.
 */
package com.meidianyi.shop.db.shop.tables.records;


import com.meidianyi.shop.db.shop.tables.DoctorDutyRecord;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 医师上下班记录表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DoctorDutyRecordRecord extends UpdatableRecordImpl<DoctorDutyRecordRecord> implements Record6<Integer, Integer, Byte, Byte, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1802035668;

    /**
     * Setter for <code>mini_shop_471752.b2c_doctor_duty_record.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_doctor_duty_record.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_doctor_duty_record.doctor_id</code>. 医师ID
     */
    public void setDoctorId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_doctor_duty_record.doctor_id</code>. 医师ID
     */
    public Integer getDoctorId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_doctor_duty_record.duty_status</code>. 上下班状态：0下班，1上班
     */
    public void setDutyStatus(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_doctor_duty_record.duty_status</code>. 上下班状态：0下班，1上班
     */
    public Byte getDutyStatus() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_doctor_duty_record.type</code>. 自动手动：0自动，1手动
     */
    public void setType(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_doctor_duty_record.type</code>. 自动手动：0自动，1手动
     */
    public Byte getType() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_doctor_duty_record.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_doctor_duty_record.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_doctor_duty_record.update_time</code>. 最后修改时间
     */
    public void setUpdateTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_doctor_duty_record.update_time</code>. 最后修改时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Byte, Byte, Timestamp, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Byte, Byte, Timestamp, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return DoctorDutyRecord.DOCTOR_DUTY_RECORD.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return DoctorDutyRecord.DOCTOR_DUTY_RECORD.DOCTOR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field3() {
        return DoctorDutyRecord.DOCTOR_DUTY_RECORD.DUTY_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field4() {
        return DoctorDutyRecord.DOCTOR_DUTY_RECORD.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return DoctorDutyRecord.DOCTOR_DUTY_RECORD.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return DoctorDutyRecord.DOCTOR_DUTY_RECORD.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getDoctorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component3() {
        return getDutyStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component4() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getDoctorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value3() {
        return getDutyStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value4() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DoctorDutyRecordRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DoctorDutyRecordRecord value2(Integer value) {
        setDoctorId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DoctorDutyRecordRecord value3(Byte value) {
        setDutyStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DoctorDutyRecordRecord value4(Byte value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DoctorDutyRecordRecord value5(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DoctorDutyRecordRecord value6(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DoctorDutyRecordRecord values(Integer value1, Integer value2, Byte value3, Byte value4, Timestamp value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DoctorDutyRecordRecord
     */
    public DoctorDutyRecordRecord() {
        super(DoctorDutyRecord.DOCTOR_DUTY_RECORD);
    }

    /**
     * Create a detached, initialised DoctorDutyRecordRecord
     */
    public DoctorDutyRecordRecord(Integer id, Integer doctorId, Byte dutyStatus, Byte type, Timestamp createTime, Timestamp updateTime) {
        super(DoctorDutyRecord.DOCTOR_DUTY_RECORD);

        set(0, id);
        set(1, doctorId);
        set(2, dutyStatus);
        set(3, type);
        set(4, createTime);
        set(5, updateTime);
    }
}
