/*
 * This file is generated by jOOQ.
 */
package com.meidianyi.shop.db.shop.tables.records;


import com.meidianyi.shop.db.shop.tables.LiveBroadcast;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LiveBroadcastRecord extends UpdatableRecordImpl<LiveBroadcastRecord> implements Record13<Integer, Integer, String, Short, Timestamp, Timestamp, String, String, String, Timestamp, Timestamp, Byte, Timestamp> {

    private static final long serialVersionUID = 2056420816;

    /**
     * Setter for <code>mini_shop_8984736.b2c_live_broadcast.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>mini_shop_8984736.b2c_live_broadcast.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>mini_shop_8984736.b2c_live_broadcast.room_id</code>. 直播间ID
     */
    public void setRoomId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>mini_shop_8984736.b2c_live_broadcast.room_id</code>. 直播间ID
     */
    public Integer getRoomId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>mini_shop_8984736.b2c_live_broadcast.name</code>. 直播间名称
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mini_shop_8984736.b2c_live_broadcast.name</code>. 直播间名称
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mini_shop_8984736.b2c_live_broadcast.live_status</code>. 直播状态 101: 直播中, 102: 未开始, 103: 已结束, 104: 禁播, 105: 暂停中, 106: 异常, 107: 已过期
     */
    public void setLiveStatus(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>mini_shop_8984736.b2c_live_broadcast.live_status</code>. 直播状态 101: 直播中, 102: 未开始, 103: 已结束, 104: 禁播, 105: 暂停中, 106: 异常, 107: 已过期
     */
    public Short getLiveStatus() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>mini_shop_8984736.b2c_live_broadcast.start_time</code>. 计划开始时间
     */
    public void setStartTime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>mini_shop_8984736.b2c_live_broadcast.start_time</code>. 计划开始时间
     */
    public Timestamp getStartTime() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>mini_shop_8984736.b2c_live_broadcast.end_time</code>. 计划结束时间
     */
    public void setEndTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>mini_shop_8984736.b2c_live_broadcast.end_time</code>. 计划结束时间
     */
    public Timestamp getEndTime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>mini_shop_8984736.b2c_live_broadcast.anchor_name</code>. 主播名
     */
    public void setAnchorName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>mini_shop_8984736.b2c_live_broadcast.anchor_name</code>. 主播名
     */
    public String getAnchorName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>mini_shop_8984736.b2c_live_broadcast.cover_img</code>. 封面图片 url
     */
    public void setCoverImg(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>mini_shop_8984736.b2c_live_broadcast.cover_img</code>. 封面图片 url
     */
    public String getCoverImg() {
        return (String) get(7);
    }

    /**
     * Setter for <code>mini_shop_8984736.b2c_live_broadcast.anchor_img</code>. 直播间图片url
     */
    public void setAnchorImg(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>mini_shop_8984736.b2c_live_broadcast.anchor_img</code>. 直播间图片url
     */
    public String getAnchorImg() {
        return (String) get(8);
    }

    /**
     * Setter for <code>mini_shop_8984736.b2c_live_broadcast.add_time</code>.
     */
    public void setAddTime(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>mini_shop_8984736.b2c_live_broadcast.add_time</code>.
     */
    public Timestamp getAddTime() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>mini_shop_8984736.b2c_live_broadcast.update_time</code>.
     */
    public void setUpdateTime(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>mini_shop_8984736.b2c_live_broadcast.update_time</code>.
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>mini_shop_8984736.b2c_live_broadcast.del_flag</code>.
     */
    public void setDelFlag(Byte value) {
        set(11, value);
    }

    /**
     * Getter for <code>mini_shop_8984736.b2c_live_broadcast.del_flag</code>.
     */
    public Byte getDelFlag() {
        return (Byte) get(11);
    }

    /**
     * Setter for <code>mini_shop_8984736.b2c_live_broadcast.del_time</code>.
     */
    public void setDelTime(Timestamp value) {
        set(12, value);
    }

    /**
     * Getter for <code>mini_shop_8984736.b2c_live_broadcast.del_time</code>.
     */
    public Timestamp getDelTime() {
        return (Timestamp) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, Integer, String, Short, Timestamp, Timestamp, String, String, String, Timestamp, Timestamp, Byte, Timestamp> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, Integer, String, Short, Timestamp, Timestamp, String, String, String, Timestamp, Timestamp, Byte, Timestamp> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return LiveBroadcast.LIVE_BROADCAST.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return LiveBroadcast.LIVE_BROADCAST.ROOM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return LiveBroadcast.LIVE_BROADCAST.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field4() {
        return LiveBroadcast.LIVE_BROADCAST.LIVE_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return LiveBroadcast.LIVE_BROADCAST.START_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return LiveBroadcast.LIVE_BROADCAST.END_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return LiveBroadcast.LIVE_BROADCAST.ANCHOR_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return LiveBroadcast.LIVE_BROADCAST.COVER_IMG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return LiveBroadcast.LIVE_BROADCAST.ANCHOR_IMG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return LiveBroadcast.LIVE_BROADCAST.ADD_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return LiveBroadcast.LIVE_BROADCAST.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field12() {
        return LiveBroadcast.LIVE_BROADCAST.DEL_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field13() {
        return LiveBroadcast.LIVE_BROADCAST.DEL_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getRoomId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component4() {
        return getLiveStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getStartTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getEndTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getAnchorName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getCoverImg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getAnchorImg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getAddTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component12() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component13() {
        return getDelTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getRoomId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value4() {
        return getLiveStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getStartTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getEndTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getAnchorName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getCoverImg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getAnchorImg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getAddTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value12() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value13() {
        return getDelTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LiveBroadcastRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LiveBroadcastRecord value2(Integer value) {
        setRoomId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LiveBroadcastRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LiveBroadcastRecord value4(Short value) {
        setLiveStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LiveBroadcastRecord value5(Timestamp value) {
        setStartTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LiveBroadcastRecord value6(Timestamp value) {
        setEndTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LiveBroadcastRecord value7(String value) {
        setAnchorName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LiveBroadcastRecord value8(String value) {
        setCoverImg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LiveBroadcastRecord value9(String value) {
        setAnchorImg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LiveBroadcastRecord value10(Timestamp value) {
        setAddTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LiveBroadcastRecord value11(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LiveBroadcastRecord value12(Byte value) {
        setDelFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LiveBroadcastRecord value13(Timestamp value) {
        setDelTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LiveBroadcastRecord values(Integer value1, Integer value2, String value3, Short value4, Timestamp value5, Timestamp value6, String value7, String value8, String value9, Timestamp value10, Timestamp value11, Byte value12, Timestamp value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LiveBroadcastRecord
     */
    public LiveBroadcastRecord() {
        super(LiveBroadcast.LIVE_BROADCAST);
    }

    /**
     * Create a detached, initialised LiveBroadcastRecord
     */
    public LiveBroadcastRecord(Integer id, Integer roomId, String name, Short liveStatus, Timestamp startTime, Timestamp endTime, String anchorName, String coverImg, String anchorImg, Timestamp addTime, Timestamp updateTime, Byte delFlag, Timestamp delTime) {
        super(LiveBroadcast.LIVE_BROADCAST);

        set(0, id);
        set(1, roomId);
        set(2, name);
        set(3, liveStatus);
        set(4, startTime);
        set(5, endTime);
        set(6, anchorName);
        set(7, coverImg);
        set(8, anchorImg);
        set(9, addTime);
        set(10, updateTime);
        set(11, delFlag);
        set(12, delTime);
    }
}
