/*
 * This file is generated by jOOQ.
 */
package com.meidianyi.shop.db.shop.tables.records;


import com.meidianyi.shop.db.shop.tables.Payment;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PaymentRecord extends UpdatableRecordImpl<PaymentRecord> implements Record11<Byte, Integer, String, String, String, String, Byte, Byte, Byte, Timestamp, Timestamp> {

    private static final long serialVersionUID = -303670487;

    /**
     * Setter for <code>mini_shop_471752.b2c_payment.id</code>.
     */
    public void setId(Byte value) {
        set(0, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_payment.id</code>.
     */
    public Byte getId() {
        return (Byte) get(0);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_payment.shop_id</code>. 店铺id
     */
    public void setShopId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_payment.shop_id</code>. 店铺id
     */
    public Integer getShopId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_payment.pay_name</code>.
     */
    public void setPayName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_payment.pay_name</code>.
     */
    public String getPayName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_payment.pay_code</code>.
     */
    public void setPayCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_payment.pay_code</code>.
     */
    public String getPayCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_payment.pay_fee</code>.
     */
    public void setPayFee(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_payment.pay_fee</code>.
     */
    public String getPayFee() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_payment.pay_desc</code>.
     */
    public void setPayDesc(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_payment.pay_desc</code>.
     */
    public String getPayDesc() {
        return (String) get(5);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_payment.enabled</code>.
     */
    public void setEnabled(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_payment.enabled</code>.
     */
    public Byte getEnabled() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_payment.is_cod</code>.
     */
    public void setIsCod(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_payment.is_cod</code>.
     */
    public Byte getIsCod() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_payment.is_online_pay</code>.
     */
    public void setIsOnlinePay(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_payment.is_online_pay</code>.
     */
    public Byte getIsOnlinePay() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_payment.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_payment.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_payment.update_time</code>. 最后修改时间
     */
    public void setUpdateTime(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_payment.update_time</code>. 最后修改时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Byte> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Byte, Integer, String, String, String, String, Byte, Byte, Byte, Timestamp, Timestamp> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Byte, Integer, String, String, String, String, Byte, Byte, Byte, Timestamp, Timestamp> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field1() {
        return Payment.PAYMENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Payment.PAYMENT.SHOP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Payment.PAYMENT.PAY_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Payment.PAYMENT.PAY_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Payment.PAYMENT.PAY_FEE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Payment.PAYMENT.PAY_DESC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field7() {
        return Payment.PAYMENT.ENABLED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field8() {
        return Payment.PAYMENT.IS_COD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field9() {
        return Payment.PAYMENT.IS_ONLINE_PAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return Payment.PAYMENT.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return Payment.PAYMENT.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getShopId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getPayName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getPayCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getPayFee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getPayDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component7() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component8() {
        return getIsCod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component9() {
        return getIsOnlinePay();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getShopId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPayName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPayCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getPayFee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getPayDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value7() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value8() {
        return getIsCod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value9() {
        return getIsOnlinePay();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value1(Byte value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value2(Integer value) {
        setShopId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value3(String value) {
        setPayName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value4(String value) {
        setPayCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value5(String value) {
        setPayFee(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value6(String value) {
        setPayDesc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value7(Byte value) {
        setEnabled(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value8(Byte value) {
        setIsCod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value9(Byte value) {
        setIsOnlinePay(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value10(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value11(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord values(Byte value1, Integer value2, String value3, String value4, String value5, String value6, Byte value7, Byte value8, Byte value9, Timestamp value10, Timestamp value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PaymentRecord
     */
    public PaymentRecord() {
        super(Payment.PAYMENT);
    }

    /**
     * Create a detached, initialised PaymentRecord
     */
    public PaymentRecord(Byte id, Integer shopId, String payName, String payCode, String payFee, String payDesc, Byte enabled, Byte isCod, Byte isOnlinePay, Timestamp createTime, Timestamp updateTime) {
        super(Payment.PAYMENT);

        set(0, id);
        set(1, shopId);
        set(2, payName);
        set(3, payCode);
        set(4, payFee);
        set(5, payDesc);
        set(6, enabled);
        set(7, isCod);
        set(8, isOnlinePay);
        set(9, createTime);
        set(10, updateTime);
    }
}
