/*
 * This file is generated by jOOQ.
 */
package com.meidianyi.shop.db.shop.tables.records;


import com.meidianyi.shop.db.shop.tables.PledgeRelated;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 服务承诺关联表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PledgeRelatedRecord extends UpdatableRecordImpl<PledgeRelatedRecord> implements Record6<Integer, Integer, Byte, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = 264761520;

    /**
     * Setter for <code>jmini_shop_666666.b2c_pledge_related.id</code>. ID
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>jmini_shop_666666.b2c_pledge_related.id</code>. ID
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>jmini_shop_666666.b2c_pledge_related.pledge_id</code>. 承诺id
     */
    public void setPledgeId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>jmini_shop_666666.b2c_pledge_related.pledge_id</code>. 承诺id
     */
    public Integer getPledgeId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>jmini_shop_666666.b2c_pledge_related.type</code>. 指定商品范围:1 商品id,2 商家分类id,3 商品品牌id
     */
    public void setType(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>jmini_shop_666666.b2c_pledge_related.type</code>. 指定商品范围:1 商品id,2 商家分类id,3 商品品牌id
     */
    public Byte getType() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>jmini_shop_666666.b2c_pledge_related.related_id</code>. 相关的id
     */
    public void setRelatedId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>jmini_shop_666666.b2c_pledge_related.related_id</code>. 相关的id
     */
    public Integer getRelatedId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>jmini_shop_666666.b2c_pledge_related.create_time</code>. 创建时间
     */
    public void setCreateTime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>jmini_shop_666666.b2c_pledge_related.create_time</code>. 创建时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>jmini_shop_666666.b2c_pledge_related.update_time</code>. 更新时间
     */
    public void setUpdateTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>jmini_shop_666666.b2c_pledge_related.update_time</code>. 更新时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Byte, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Byte, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return PledgeRelated.PLEDGE_RELATED.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return PledgeRelated.PLEDGE_RELATED.PLEDGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field3() {
        return PledgeRelated.PLEDGE_RELATED.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return PledgeRelated.PLEDGE_RELATED.RELATED_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return PledgeRelated.PLEDGE_RELATED.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return PledgeRelated.PLEDGE_RELATED.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getPledgeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getRelatedId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getPledgeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getRelatedId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PledgeRelatedRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PledgeRelatedRecord value2(Integer value) {
        setPledgeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PledgeRelatedRecord value3(Byte value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PledgeRelatedRecord value4(Integer value) {
        setRelatedId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PledgeRelatedRecord value5(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PledgeRelatedRecord value6(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PledgeRelatedRecord values(Integer value1, Integer value2, Byte value3, Integer value4, Timestamp value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PledgeRelatedRecord
     */
    public PledgeRelatedRecord() {
        super(PledgeRelated.PLEDGE_RELATED);
    }

    /**
     * Create a detached, initialised PledgeRelatedRecord
     */
    public PledgeRelatedRecord(Integer id, Integer pledgeId, Byte type, Integer relatedId, Timestamp createTime, Timestamp updateTime) {
        super(PledgeRelated.PLEDGE_RELATED);

        set(0, id);
        set(1, pledgeId);
        set(2, type);
        set(3, relatedId);
        set(4, createTime);
        set(5, updateTime);
    }
}
