/*
 * This file is generated by jOOQ.
 */
package com.meidianyi.shop.db.shop.tables.records;


import com.meidianyi.shop.db.shop.tables.WxpUnlimitCode;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WxpUnlimitCodeRecord extends UpdatableRecordImpl<WxpUnlimitCodeRecord> implements Record9<Integer, String, String, String, String, Timestamp, Timestamp, Byte, Timestamp> {

    private static final long serialVersionUID = -1865027057;

    /**
     * Setter for <code>mini_shop_471752.b2c_wxp_unlimit_code.code_id</code>. 小程序码id
     */
    public void setCodeId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_wxp_unlimit_code.code_id</code>. 小程序码id
     */
    public Integer getCodeId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_wxp_unlimit_code.scene_id</code>. 对应b2c_wxp_unlimit_scene的scene_id
     */
    public void setSceneId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_wxp_unlimit_code.scene_id</code>. 对应b2c_wxp_unlimit_scene的scene_id
     */
    public String getSceneId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_wxp_unlimit_code.code_page</code>. 必须是已经发布的小程序存在的页面（否则报错），例如 pages/index/index, 根路径前不要填加 /,不能携带参数（参数请放在scene字段里），如果不填写这个字段，默认跳主页面
     */
    public void setCodePage(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_wxp_unlimit_code.code_page</code>. 必须是已经发布的小程序存在的页面（否则报错），例如 pages/index/index, 根路径前不要填加 /,不能携带参数（参数请放在scene字段里），如果不填写这个字段，默认跳主页面
     */
    public String getCodePage() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_wxp_unlimit_code.code_url</code>. 小程序码url
     */
    public void setCodeUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_wxp_unlimit_code.code_url</code>. 小程序码url
     */
    public String getCodeUrl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_wxp_unlimit_code.code_path</code>. 小程序码本地地址
     */
    public void setCodePath(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_wxp_unlimit_code.code_path</code>. 小程序码本地地址
     */
    public String getCodePath() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_wxp_unlimit_code.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_wxp_unlimit_code.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_wxp_unlimit_code.update_time</code>. 最后修改时间
     */
    public void setUpdateTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_wxp_unlimit_code.update_time</code>. 最后修改时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_wxp_unlimit_code.del_flag</code>.
     */
    public void setDelFlag(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_wxp_unlimit_code.del_flag</code>.
     */
    public Byte getDelFlag() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_wxp_unlimit_code.del_time</code>. 删除时间
     */
    public void setDelTime(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_wxp_unlimit_code.del_time</code>. 删除时间
     */
    public Timestamp getDelTime() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, String, String, Timestamp, Timestamp, Byte, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, String, String, Timestamp, Timestamp, Byte, Timestamp> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return WxpUnlimitCode.WXP_UNLIMIT_CODE.CODE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return WxpUnlimitCode.WXP_UNLIMIT_CODE.SCENE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return WxpUnlimitCode.WXP_UNLIMIT_CODE.CODE_PAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return WxpUnlimitCode.WXP_UNLIMIT_CODE.CODE_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return WxpUnlimitCode.WXP_UNLIMIT_CODE.CODE_PATH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return WxpUnlimitCode.WXP_UNLIMIT_CODE.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return WxpUnlimitCode.WXP_UNLIMIT_CODE.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field8() {
        return WxpUnlimitCode.WXP_UNLIMIT_CODE.DEL_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return WxpUnlimitCode.WXP_UNLIMIT_CODE.DEL_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getCodeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getSceneId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCodePage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCodeUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getCodePath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component8() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getDelTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getCodeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSceneId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCodePage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCodeUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCodePath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value8() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getDelTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxpUnlimitCodeRecord value1(Integer value) {
        setCodeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxpUnlimitCodeRecord value2(String value) {
        setSceneId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxpUnlimitCodeRecord value3(String value) {
        setCodePage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxpUnlimitCodeRecord value4(String value) {
        setCodeUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxpUnlimitCodeRecord value5(String value) {
        setCodePath(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxpUnlimitCodeRecord value6(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxpUnlimitCodeRecord value7(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxpUnlimitCodeRecord value8(Byte value) {
        setDelFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxpUnlimitCodeRecord value9(Timestamp value) {
        setDelTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxpUnlimitCodeRecord values(Integer value1, String value2, String value3, String value4, String value5, Timestamp value6, Timestamp value7, Byte value8, Timestamp value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WxpUnlimitCodeRecord
     */
    public WxpUnlimitCodeRecord() {
        super(WxpUnlimitCode.WXP_UNLIMIT_CODE);
    }

    /**
     * Create a detached, initialised WxpUnlimitCodeRecord
     */
    public WxpUnlimitCodeRecord(Integer codeId, String sceneId, String codePage, String codeUrl, String codePath, Timestamp createTime, Timestamp updateTime, Byte delFlag, Timestamp delTime) {
        super(WxpUnlimitCode.WXP_UNLIMIT_CODE);

        set(0, codeId);
        set(1, sceneId);
        set(2, codePage);
        set(3, codeUrl);
        set(4, codePath);
        set(5, createTime);
        set(6, updateTime);
        set(7, delFlag);
        set(8, delTime);
    }
}
