package com.meidianyi.shop.service.wechat.bean.ma;


import lombok.Getter;

/**
 * 
 * @author zhaojianqiang
 *
 * 2019年8月19日 下午5:51:04
 */
@Getter
public enum  WxContentTemplate {

	WX_GET_TESTER_QR_FAIL(2000,WxContentMessage.WX_GET_TESTER_QR_FAIL),
	WX_GET_TESTER_QR_SUCCESS(2001,WxContentMessage.WX_GET_TESTER_QR_SUCCESS),
	
	WX_BIND_TESTER_FAIL(2002,WxContentMessage.WX_BIND_TESTER_FAIL),
	WX_BIND_TESTER_SUCCESS(2003,WxContentMessage.WX_BIND_TESTER_SUCCESS),
	
	WX_DEL_TESTER_FAIL(2004,WxContentMessage.WX_DEL_TESTER_FAIL),
	WX_DEL_TESTER_SUCCESS(2005,WxContentMessage.WX_DEL_TESTER_SUCCESS),
	
	WX_GET_PAGE_CFG_FAIL(2006,WxContentMessage.WX_GET_PAGE_CFG_FAIL),
	WX_GET_PAGE_CFG_SUCCESS(2007,WxContentMessage.WX_GET_PAGE_CFG_SUCCESS),
	
	WX_GET_NO_RECORD_FAIL(2008,WxContentMessage.WX_GET_NO_RECORD_FAIL),
	WX_GET_NO_RECORD_SUCCESS(2009,WxContentMessage.WX_GET_NO_RECORD_SUCCESS),
	
	
	WX_MODIFY_DOMAIN_FAIL(2010,WxContentMessage.WX_MODIFY_DOMAIN_FAIL),
	WX_MODIFY_DOMAIN_SUCCESS(2011,WxContentMessage.WX_MODIFY_DOMAIN_SUCCESS),
	
	WX_PUBLISH_CODE_FAIL(2012,WxContentMessage.WX_PUBLISH_CODE_FAIL),
	WX_PUBLISH_CODE_SUCCESS(2013,WxContentMessage.WX_PUBLISH_CODE_SUCCESS),
	
	WX_SUBMIT_AUDIT_FAIL(2014,WxContentMessage.WX_SUBMIT_AUDIT_FAIL),
	WX_SUBMIT_AUDIT_SUCCESS(2015,WxContentMessage.WX_SUBMIT_AUDIT_SUCCESS),
	
	WX_GET_CATEGORY_FAIL(2016,WxContentMessage.WX_GET_CATEGORY_FAIL),
	WX_GET_CATEGORY_SUCCESS(2017,WxContentMessage.WX_GET_CATEGORY_SUCCESS),
	
	WX_UPDATE_MP_FAIL(2018,WxContentMessage.WX_UPDATE_MP_FAIL),
	WX_UPDATE_MP_SUCCESS(2019,WxContentMessage.WX_UPDATE_MP_SUCCESS),
	
	
	WX_UPLOAD_AUDIT_FAIL(2020,WxContentMessage.WX_UPLOAD_AUDIT_FAIL),
	WX_UPLOAD_AUDIT_SUCCESS(2021,WxContentMessage.WX_UPLOAD_AUDIT_SUCCESS),
	
	WX_UPLOAD_CODE_FAIL(2022,WxContentMessage.WX_UPLOAD_CODE_FAIL),
	WX_UPLOAD_CODE_SUCCESS(2023,WxContentMessage.WX_UPLOAD_CODE_SUCCESS),
	
	WX_SETTING_SUB_MERCHANT_FAIL(2024,WxContentMessage.WX_SETTING_SUB_MERCHANT_FAIL),
	WX_SETTING_SUB_MERCHANT_SUCCESS(2025,WxContentMessage.WX_SETTING_SUB_MERCHANT_SUCCESS),
	
	
	WX_REFRESH_AUDIT_STATE_FAIL(2026,WxContentMessage.WX_REFRESH_AUDIT_STATE_FAIL),
	WX_REFRESH_AUDIT_STATE_SUCCESS(2027,WxContentMessage.WX_REFRESH_AUDIT_STATE_SUCCESS),
	WX_REFRESH_AUDIT_STATE_SUCCESSON2(2028,WxContentMessage.WX_REFRESH_AUDIT_STATE_SUCCESSON2),
	
	WX_TABLE_ISNULL(404,WxContentMessage.WX_TABLE_ISNULL),
	WX_FEATURE_NOT_OPEN(403,WxContentMessage.WX_FEATURE_NOT_OPEN),
	
	
	WX_AUDIT_FAIL(2028,WxContentMessage.WX_AUDIT_FAIL),
	WX_AUDIT_SUCCESS(2029,WxContentMessage.WX_AUDIT_SUCCESS),
	
	WX_ERROE(500,WxContentMessage.WX_ERROE);
	

	
    /**
     * 得到返回码
	 */
    public int code;

    /**
     * 返回信息
     */
    private String message;

     WxContentTemplate(int code, String message) {
        this.code = code;
        this.message = message;
    }

}
