/*
 * This file is generated by jOOQ.
 */
package com.meidianyi.shop.db.shop.tables;


import com.meidianyi.shop.db.shop.Indexes;
import com.meidianyi.shop.db.shop.Keys;
import com.meidianyi.shop.db.shop.MiniShop_471752;
import com.meidianyi.shop.db.shop.tables.records.BatchProfitRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BatchProfit extends TableImpl<BatchProfitRecord> {

    private static final long serialVersionUID = -2010970026;

    /**
     * The reference instance of <code>mini_shop_471752.b2c_batch_profit</code>
     */
    public static final BatchProfit BATCH_PROFIT = new BatchProfit();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BatchProfitRecord> getRecordType() {
        return BatchProfitRecord.class;
    }

    /**
     * The column <code>mini_shop_471752.b2c_batch_profit.id</code>.
     */
    public final TableField<BatchProfitRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>mini_shop_471752.b2c_batch_profit.brand_id</code>. 品牌id
     */
    public final TableField<BatchProfitRecord, Integer> BRAND_ID = createField("brand_id", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "品牌id");

    /**
     * The column <code>mini_shop_471752.b2c_batch_profit.sort_id</code>. 分类id
     */
    public final TableField<BatchProfitRecord, Integer> SORT_ID = createField("sort_id", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "分类id");

    /**
     * The column <code>mini_shop_471752.b2c_batch_profit.act_id</code>. 导入批次
     */
    public final TableField<BatchProfitRecord, Integer> ACT_ID = createField("act_id", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.INTEGER)), this, "导入批次");

    /**
     * The column <code>mini_shop_471752.b2c_batch_profit.profit_per</code>.
     */
    public final TableField<BatchProfitRecord, BigDecimal> PROFIT_PER = createField("profit_per", org.jooq.impl.SQLDataType.DECIMAL(10, 2).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DECIMAL)), this, "");

    /**
     * The column <code>mini_shop_471752.b2c_batch_profit.file_name</code>. 文件名称
     */
    public final TableField<BatchProfitRecord, String> FILE_NAME = createField("file_name", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "文件名称");

    /**
     * The column <code>mini_shop_471752.b2c_batch_profit.create_time</code>.
     */
    public final TableField<BatchProfitRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>mini_shop_471752.b2c_batch_profit.update_time</code>. 最后修改时间
     */
    public final TableField<BatchProfitRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "最后修改时间");

    /**
     * Create a <code>mini_shop_471752.b2c_batch_profit</code> table reference
     */
    public BatchProfit() {
        this(DSL.name("b2c_batch_profit"), null);
    }

    /**
     * Create an aliased <code>mini_shop_471752.b2c_batch_profit</code> table reference
     */
    public BatchProfit(String alias) {
        this(DSL.name(alias), BATCH_PROFIT);
    }

    /**
     * Create an aliased <code>mini_shop_471752.b2c_batch_profit</code> table reference
     */
    public BatchProfit(Name alias) {
        this(alias, BATCH_PROFIT);
    }

    private BatchProfit(Name alias, Table<BatchProfitRecord> aliased) {
        this(alias, aliased, null);
    }

    private BatchProfit(Name alias, Table<BatchProfitRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> BatchProfit(Table<O> child, ForeignKey<O, BatchProfitRecord> key) {
        super(child, key, BATCH_PROFIT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MiniShop_471752.MINI_SHOP_471752;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.BATCH_PROFIT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<BatchProfitRecord, Integer> getIdentity() {
        return Keys.IDENTITY_BATCH_PROFIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BatchProfitRecord> getPrimaryKey() {
        return Keys.KEY_B2C_BATCH_PROFIT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BatchProfitRecord>> getKeys() {
        return Arrays.<UniqueKey<BatchProfitRecord>>asList(Keys.KEY_B2C_BATCH_PROFIT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchProfit as(String alias) {
        return new BatchProfit(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchProfit as(Name alias) {
        return new BatchProfit(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public BatchProfit rename(String name) {
        return new BatchProfit(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BatchProfit rename(Name name) {
        return new BatchProfit(name, null);
    }
}
