/*
 * This file is generated by jOOQ.
 */
package com.meidianyi.shop.db.shop.tables;


import com.meidianyi.shop.db.shop.Indexes;
import com.meidianyi.shop.db.shop.Keys;
import com.meidianyi.shop.db.shop.MiniShop_471752;
import com.meidianyi.shop.db.shop.tables.records.GoodsSummaryRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GoodsSummary extends TableImpl<GoodsSummaryRecord> {

    private static final long serialVersionUID = -1764038200;

    /**
     * The reference instance of <code>mini_shop_471752.b2c_goods_summary</code>
     */
    public static final GoodsSummary GOODS_SUMMARY = new GoodsSummary();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GoodsSummaryRecord> getRecordType() {
        return GoodsSummaryRecord.class;
    }

    /**
     * The column <code>mini_shop_471752.b2c_goods_summary.id</code>.
     */
    public final TableField<GoodsSummaryRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>mini_shop_471752.b2c_goods_summary.ref_date</code>. 统计日期
     */
    public final TableField<GoodsSummaryRecord, Date> REF_DATE = createField("ref_date", org.jooq.impl.SQLDataType.DATE, this, "统计日期");

    /**
     * The column <code>mini_shop_471752.b2c_goods_summary.type</code>. 1,7,30
     */
    public final TableField<GoodsSummaryRecord, Byte> TYPE = createField("type", org.jooq.impl.SQLDataType.TINYINT, this, "1,7,30");

    /**
     * The column <code>mini_shop_471752.b2c_goods_summary.goods_id</code>.
     */
    public final TableField<GoodsSummaryRecord, Integer> GOODS_ID = createField("goods_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>mini_shop_471752.b2c_goods_summary.new_user_number</code>. 新成交客户数
     */
    public final TableField<GoodsSummaryRecord, Integer> NEW_USER_NUMBER = createField("new_user_number", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "新成交客户数");

    /**
     * The column <code>mini_shop_471752.b2c_goods_summary.old_user_number</code>. 老成交客户数
     */
    public final TableField<GoodsSummaryRecord, Integer> OLD_USER_NUMBER = createField("old_user_number", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "老成交客户数");

    /**
     * The column <code>mini_shop_471752.b2c_goods_summary.pv</code>. 浏览量
     */
    public final TableField<GoodsSummaryRecord, Integer> PV = createField("pv", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "浏览量");

    /**
     * The column <code>mini_shop_471752.b2c_goods_summary.uv</code>. 访客数
     */
    public final TableField<GoodsSummaryRecord, Integer> UV = createField("uv", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "访客数");

    /**
     * The column <code>mini_shop_471752.b2c_goods_summary.cart_uv</code>. 加购人数
     */
    public final TableField<GoodsSummaryRecord, Integer> CART_UV = createField("cart_uv", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "加购人数");

    /**
     * The column <code>mini_shop_471752.b2c_goods_summary.paid_uv</code>. 付款人数
     */
    public final TableField<GoodsSummaryRecord, Integer> PAID_UV = createField("paid_uv", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "付款人数");

    /**
     * The column <code>mini_shop_471752.b2c_goods_summary.paid_goods_number</code>. 付款商品件数
     */
    public final TableField<GoodsSummaryRecord, Integer> PAID_GOODS_NUMBER = createField("paid_goods_number", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "付款商品件数");

    /**
     * The column <code>mini_shop_471752.b2c_goods_summary.goods_sales</code>. 销售额
     */
    public final TableField<GoodsSummaryRecord, BigDecimal> GOODS_SALES = createField("goods_sales", org.jooq.impl.SQLDataType.DECIMAL(10, 2).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DECIMAL)), this, "销售额");

    /**
     * The column <code>mini_shop_471752.b2c_goods_summary.recommend_user_num</code>. 推荐人数
     */
    public final TableField<GoodsSummaryRecord, Integer> RECOMMEND_USER_NUM = createField("recommend_user_num", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "推荐人数");

    /**
     * The column <code>mini_shop_471752.b2c_goods_summary.collect_use_num</code>. 收藏人数
     */
    public final TableField<GoodsSummaryRecord, Integer> COLLECT_USE_NUM = createField("collect_use_num", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "收藏人数");

    /**
     * The column <code>mini_shop_471752.b2c_goods_summary.share_pv</code>. 分享次数
     */
    public final TableField<GoodsSummaryRecord, Integer> SHARE_PV = createField("share_pv", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "分享次数");

    /**
     * The column <code>mini_shop_471752.b2c_goods_summary.share_uv</code>. 分享人数
     */
    public final TableField<GoodsSummaryRecord, Integer> SHARE_UV = createField("share_uv", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "分享人数");

    /**
     * The column <code>mini_shop_471752.b2c_goods_summary.create_time</code>.
     */
    public final TableField<GoodsSummaryRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>mini_shop_471752.b2c_goods_summary.update_time</code>. 最后修改时间
     */
    public final TableField<GoodsSummaryRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "最后修改时间");

    /**
     * Create a <code>mini_shop_471752.b2c_goods_summary</code> table reference
     */
    public GoodsSummary() {
        this(DSL.name("b2c_goods_summary"), null);
    }

    /**
     * Create an aliased <code>mini_shop_471752.b2c_goods_summary</code> table reference
     */
    public GoodsSummary(String alias) {
        this(DSL.name(alias), GOODS_SUMMARY);
    }

    /**
     * Create an aliased <code>mini_shop_471752.b2c_goods_summary</code> table reference
     */
    public GoodsSummary(Name alias) {
        this(alias, GOODS_SUMMARY);
    }

    private GoodsSummary(Name alias, Table<GoodsSummaryRecord> aliased) {
        this(alias, aliased, null);
    }

    private GoodsSummary(Name alias, Table<GoodsSummaryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> GoodsSummary(Table<O> child, ForeignKey<O, GoodsSummaryRecord> key) {
        super(child, key, GOODS_SUMMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MiniShop_471752.MINI_SHOP_471752;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.GOODS_SUMMARY_PRIMARY, Indexes.GOODS_SUMMARY_UNI_KEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<GoodsSummaryRecord, Integer> getIdentity() {
        return Keys.IDENTITY_GOODS_SUMMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GoodsSummaryRecord> getPrimaryKey() {
        return Keys.KEY_B2C_GOODS_SUMMARY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GoodsSummaryRecord>> getKeys() {
        return Arrays.<UniqueKey<GoodsSummaryRecord>>asList(Keys.KEY_B2C_GOODS_SUMMARY_PRIMARY, Keys.KEY_B2C_GOODS_SUMMARY_UNI_KEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsSummary as(String alias) {
        return new GoodsSummary(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsSummary as(Name alias) {
        return new GoodsSummary(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public GoodsSummary rename(String name) {
        return new GoodsSummary(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GoodsSummary rename(Name name) {
        return new GoodsSummary(name, null);
    }
}
