/*
 * This file is generated by jOOQ.
 */
package com.meidianyi.shop.db.shop.tables;


import com.meidianyi.shop.db.shop.Indexes;
import com.meidianyi.shop.db.shop.Keys;
import com.meidianyi.shop.db.shop.MiniShop_471752;
import com.meidianyi.shop.db.shop.tables.records.MpDistributionVisitRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * 访问分布
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MpDistributionVisit extends TableImpl<MpDistributionVisitRecord> {

    private static final long serialVersionUID = 1588271582;

    /**
     * The reference instance of <code>jmini_shop_666666.b2c_mp_distribution_visit</code>
     */
    public static final MpDistributionVisit MP_DISTRIBUTION_VISIT = new MpDistributionVisit();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MpDistributionVisitRecord> getRecordType() {
        return MpDistributionVisitRecord.class;
    }

    /**
     * The column <code>jmini_shop_666666.b2c_mp_distribution_visit.ref_date</code>. 时间，如："20180313"
     */
    public final TableField<MpDistributionVisitRecord, String> REF_DATE = createField("ref_date", org.jooq.impl.SQLDataType.CHAR(8).nullable(false), this, "时间，如：\"20180313\"");

    /**
     * The column <code>jmini_shop_666666.b2c_mp_distribution_visit.list</code>. 存入所有类型的指标情况
     */
    public final TableField<MpDistributionVisitRecord, String> LIST = createField("list", org.jooq.impl.SQLDataType.CLOB, this, "存入所有类型的指标情况");

    /**
     * The column <code>jmini_shop_666666.b2c_mp_distribution_visit.create_time</code>.
     */
    public final TableField<MpDistributionVisitRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>jmini_shop_666666.b2c_mp_distribution_visit.update_time</code>. 最后修改时间
     */
    public final TableField<MpDistributionVisitRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "最后修改时间");

    /**
     * The column <code>jmini_shop_666666.b2c_mp_distribution_visit.id</code>.
     */
    public final TableField<MpDistributionVisitRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * Create a <code>jmini_shop_666666.b2c_mp_distribution_visit</code> table reference
     */
    public MpDistributionVisit() {
        this(DSL.name("b2c_mp_distribution_visit"), null);
    }

    /**
     * Create an aliased <code>jmini_shop_666666.b2c_mp_distribution_visit</code> table reference
     */
    public MpDistributionVisit(String alias) {
        this(DSL.name(alias), MP_DISTRIBUTION_VISIT);
    }

    /**
     * Create an aliased <code>jmini_shop_666666.b2c_mp_distribution_visit</code> table reference
     */
    public MpDistributionVisit(Name alias) {
        this(alias, MP_DISTRIBUTION_VISIT);
    }

    private MpDistributionVisit(Name alias, Table<MpDistributionVisitRecord> aliased) {
        this(alias, aliased, null);
    }

    private MpDistributionVisit(Name alias, Table<MpDistributionVisitRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("访问分布"));
    }

    public <O extends Record> MpDistributionVisit(Table<O> child, ForeignKey<O, MpDistributionVisitRecord> key) {
        super(child, key, MP_DISTRIBUTION_VISIT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MiniShop_471752.MINI_SHOP_471752;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.MP_DISTRIBUTION_VISIT_PRIMARY, Indexes.MP_DISTRIBUTION_VISIT_REF_DATE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<MpDistributionVisitRecord, Integer> getIdentity() {
        return Keys.IDENTITY_MP_DISTRIBUTION_VISIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MpDistributionVisitRecord> getPrimaryKey() {
        return Keys.KEY_B2C_MP_DISTRIBUTION_VISIT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MpDistributionVisitRecord>> getKeys() {
        return Arrays.<UniqueKey<MpDistributionVisitRecord>>asList(Keys.KEY_B2C_MP_DISTRIBUTION_VISIT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MpDistributionVisit as(String alias) {
        return new MpDistributionVisit(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MpDistributionVisit as(Name alias) {
        return new MpDistributionVisit(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MpDistributionVisit rename(String name) {
        return new MpDistributionVisit(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MpDistributionVisit rename(Name name) {
        return new MpDistributionVisit(name, null);
    }
}
